# Generated by Django 6.0.3 on 2026-03-14 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("donor", "Donor"),
                    ("ngo", "NGO / Volunteer"),
                    ("needy_person", "Needy Person"),
                    ("admin", "Admin"),
                ],
                default="donor",
                max_length=15,
            ),
        ),
    ]
