# Generated by Django 6.0.3 on 2026-06-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("donor", "Donor"),
                    ("ngo", "NGO / Volunteer"),
                    ("needy", "Needy Person"),
                    ("admin", "Admin"),
                ],
                default="donor",
                max_length=10,
            ),
        ),
    ]
